export const huruikeya = [
  {
    word_id: 1523740,
    word_type: 'KNOWN',
    word_position: 1,
    surface_form: '古池',
    pos: '名詞',
    pos_detail_1: '固有名詞',
    pos_detail_2: '地域',
    pos_detail_3: '一般',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '古池',
    reading: 'フルイケ',
    pronunciation: 'フルイケ',
  },
  {
    word_id: 92870,
    word_type: 'KNOWN',
    word_position: 3,
    surface_form: 'や',
    pos: '助詞',
    pos_detail_1: '並立助詞',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'や',
    reading: 'ヤ',
    pronunciation: 'ヤ',
    head: false,
  },
  {
    word_id: 764680,
    word_type: 'KNOWN',
    word_position: 4,
    surface_form: '蛙',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '蛙',
    reading: 'カエル',
    pronunciation: 'カエル',
  },
  {
    word_id: 1829930,
    word_type: 'KNOWN',
    word_position: 5,
    surface_form: '飛び込む',
    pos: '動詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '五段・マ行',
    conjugated_form: '基本形',
    basic_form: '飛び込む',
    reading: 'トビコム',
    pronunciation: 'トビコム',
  },
  {
    word_id: 2121210,
    word_type: 'KNOWN',
    word_position: 9,
    surface_form: '水',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '水',
    reading: 'ミズ',
    pronunciation: 'ミズ',
  },
  {
    word_id: 93100,
    word_type: 'KNOWN',
    word_position: 10,
    surface_form: 'の',
    pos: '助詞',
    pos_detail_1: '連体化',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'の',
    reading: 'ノ',
    pronunciation: 'ノ',
    head: false,
  },
  {
    word_id: 2279520,
    word_type: 'KNOWN',
    word_position: 11,
    surface_form: '音',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '音',
    reading: 'オト',
    pronunciation: 'オト',
  },
];

export const sumomo = [
  {
    word_id: 415760,
    word_type: 'KNOWN',
    word_position: 1,
    surface_form: 'すもも',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'すもも',
    reading: 'スモモ',
    pronunciation: 'スモモ',
  },
  {
    word_id: 93220,
    word_type: 'KNOWN',
    word_position: 4,
    surface_form: 'も',
    pos: '助詞',
    pos_detail_1: '係助詞',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'も',
    reading: 'モ',
    pronunciation: 'モ',
    head: false,
  },
  {
    word_id: 1614710,
    word_type: 'KNOWN',
    word_position: 5,
    surface_form: 'もも',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'もも',
    reading: 'モモ',
    pronunciation: 'モモ',
  },
  {
    word_id: 93220,
    word_type: 'KNOWN',
    word_position: 7,
    surface_form: 'も',
    pos: '助詞',
    pos_detail_1: '係助詞',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'も',
    reading: 'モ',
    pronunciation: 'モ',
    head: false,
  },
  {
    word_id: 1614710,
    word_type: 'KNOWN',
    word_position: 8,
    surface_form: 'もも',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'もも',
    reading: 'モモ',
    pronunciation: 'モモ',
  },
  {
    word_id: 93100,
    word_type: 'KNOWN',
    word_position: 10,
    surface_form: 'の',
    pos: '助詞',
    pos_detail_1: '連体化',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'の',
    reading: 'ノ',
    pronunciation: 'ノ',
    head: false,
  },
  {
    word_id: 62510,
    word_type: 'KNOWN',
    word_position: 11,
    surface_form: 'うち',
    pos: '名詞',
    pos_detail_1: '非自立',
    pos_detail_2: '副詞可能',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'うち',
    reading: 'ウチ',
    pronunciation: 'ウチ',
  },
];

export const anonatsu = [
  {
    word_id: 13310,
    word_type: 'KNOWN',
    word_position: 9,
    surface_form: 'あの',
    pos: '連体詞',
    pos_detail_1: '*',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'あの',
    reading: 'アノ',
    pronunciation: 'アノ',
    head: true,
    tail: true,
  },
  {
    word_id: 2229530,
    word_type: 'KNOWN',
    word_position: 11,
    surface_form: '夏',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '夏',
    reading: 'ナツ',
    pronunciation: 'ナツ',
    head: true,
    tail: true,
  },
  {
    word_id: 93100,
    word_type: 'KNOWN',
    word_position: 12,
    surface_form: 'の',
    pos: '助詞',
    pos_detail_1: '連体化',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'の',
    reading: 'ノ',
    pronunciation: 'ノ',
    head: false,
    tail: true,
  },
  {
    word_id: 2490850,
    word_type: 'KNOWN',
    word_position: 14,
    surface_form: '学級',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '学級',
    reading: 'ガッキュウ',
    pronunciation: 'ガッキュー',
    head: true,
    tail: true,
  },
  {
    word_id: 2767120,
    word_type: 'KNOWN',
    word_position: 16,
    surface_form: '文庫',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '文庫',
    reading: 'ブンコ',
    pronunciation: 'ブンコ',
    head: true,
    tail: true,
  },
  {
    word_id: 704820,
    word_type: 'KNOWN',
    word_position: 19,
    surface_form: '取り出し',
    pos: '動詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '五段・サ行',
    conjugated_form: '連用形',
    basic_form: '取り出す',
    reading: 'トリダシ',
    pronunciation: 'トリダシ',
    head: true,
    tail: true,
  },
  {
    word_id: 92780,
    word_type: 'KNOWN',
    word_position: 23,
    surface_form: 'て',
    pos: '助詞',
    pos_detail_1: '接続助詞',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'て',
    reading: 'テ',
    pronunciation: 'テ',
    head: false,
    tail: true,
  },
];
